### ISSUE TITLE
I am getting this error while switching from ES 5.4.1 to ES 5.5.1

### ISSUE THREAD

**Issue by pinki2807** [skmonga/X-Pack-spring-security-realm#1]
I am getting below exception:

D: /..elasticsearch-5.5.1\bin\x-pack>extension install file:///D:/.../spring-security-x-pack-realm.zip
-> Downloading file:///D:/.../spring-security-x-pack-realm.zip
Exception in thread "main" java.nio.file.NoSuchFileException: D:...\elasticsearch-5.5.1\plugins\x-pack\extensions.installing-5210527504536241974\x-pack-extension-descriptor.properties
at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
at java.nio.file.Files.newByteChannel(Files.java:361)
at java.nio.file.Files.newByteChannel(Files.java:407)
at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
at java.nio.file.Files.newInputStream(Files.java:152)
at org.elasticsearch.xpack.extensions.XPackExtensionInfo.readFromProperties(XPackExtensionInfo.java:59)
at org.elasticsearch.xpack.extensions.InstallXPackExtensionCommand.verify(InstallXPackExtensionCommand.java:163)
at org.elasticsearch.xpack.extensions.InstallXPackExtensionCommand.install(InstallXPackExtensionCommand.java:204)
at org.elasticsearch.xpack.extensions.InstallXPackExtensionCommand.execute(InstallXPackExtensionCommand.java:114)
at org.elasticsearch.xpack.extensions.InstallXPackExtensionCommand.execute(InstallXPackExtensionCommand.java:101)
at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:69)
at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
at org.elasticsearch.cli.Command.main(Command.java:88)
at org.elasticsearch.xpack.extensions.XPackExtensionCli.main(XPackExtensionCli.java:36)

**Comment by skmonga** [comment]
@pinki2807 did you create the zip with the jar + policy + descriptor properties file. If not do that. Also when migrating from ES 5.4.1 to ES 5.5.1 , you need to change the xpack.version property to the correct version to which you are migrating. Also do change the artifacts version in the pom.xml to the same version of ES as well.

**Comment by pinki2807** [comment]
Thanks @skmonga 
What command should I use for packaging?

**Comment by skmonga** [comment]
You need to create a zip file of the jar + policy file + descriptor.properties file and install from that zip via extension install file://${path to the zip}

**Comment by pinki2807** [comment]
While creating jar I am getting this:
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:01 min
[INFO] Finished at: 2018-03-12T16:37:23+05:30
[INFO] Final Memory: 13M/303M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project shieldOAuth: Could not resolve dependencies for project com.nucleus:shieldOAuth:jar:0.2.6-SNAPSHOT: The following artifacts could not be resolved: org.elasticsearch:elasticsearch:jar:5.4.2, org.elasticsearch.plugin:x-pack-api:jar:5.4.2, org.elasticsearch.client:x-pack-transport:jar:5.4.2, org.apache.lucene:lucene-test-framework:jar:6.5.1: Could not find artifact org.elasticsearch:elasticsearch:jar:5.4.2 in nexus
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.

**Comment by skmonga** [comment]
You need to change the version of the dependencies to the version of ES you are running. Also since the error suggests artifacts not found, you may be getting the artifacts only from your local nexus repo. The elasticsearch and xpack specific artifacts are hosted on elastic own repo so you need to able to connect to it and download those. Check if you can do that via some proxy and correct the version to 5.5.1

**Comment by pinki2807** [comment]
After changing version from 5.4.1 to 5.5.1 I am getting Exception in below method  

 @Override
    public User authenticate(AuthenticationToken authenticationToken) {
        UsernamePasswordToken token = (UsernamePasswordToken) authenticationToken;
        final String actualUser = token.principal();
        final InfoHolder info = usersMap.get(actualUser);

        if (info != null && SecuredString.constantTimeEquals(token.credentials(), info.password)) {
            return new User(actualUser, info.roles);
        }
        return null;
    }

**Error is:**

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 39.197 s
[INFO] Finished at: 2018-03-13T14:25:24+05:30
[INFO] Final Memory: 25M/66M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5:compile (default-compile) on project shieldOAuth: Compilation failure: Compilation failure:
[ERROR] D:\...\x-pack-custom-realm\src\main\java\org\elasticsearch\example\realm\CustomRealm.java:[30,53] error: cannot find symbol
[ERROR] symbol:   class SecuredString
[ERROR] location: package org.elasticsearch.xpack.security.authc.support
[ERROR] D:\...\x-pack-custom-realm\src\main\java\org\elasticsearch\example\realm\CustomCachingRealm.java:[26,53] error: cannot find symbol
[ERROR] -> [Help 1]
[ERROR]


Secured class in not available in other ES versions What should I use instead of 
 SecuredString.constantTimeEquals(token.credentials(), info.password)

**Comment by pinki2807** [comment]
For now I am using 5.4.0 version which has SecuredString class
